name: main

on:
  push:
    # Publish `main` as `latest` tag.
    branches:
      - main

    # Publish version tags.
    tags:
      - v*

jobs:

  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: terminusdb/terminusdb
          path: terminusdb

      - name: Build (base)
        run: docker build . --tag terminusdb/terminusdb-builder:base

      - name: Build (test)
        run: >
          cat "FROM terminusdb/terminusdb-builder:base\nRUN make install-deps" | \
            docker build . --tag terminusdb/terminusdb-builder:test

      - name: Lint (test)
        run: >
          docker run \
            --rm \
            --volume $(pwd)/terminusdb:/app/terminusdb \
            --workdir /app/terminusdb \
            terminusdb/terminusdb-builder:test \
            make lint

      - name: Unit tests (test)
        run: >
          docker run \
            --rm \
            --volume $(pwd)/terminusdb:/app/terminusdb \
            --workdir /app/terminusdb \
            terminusdb/terminusdb-builder:test \
            make test
