name: Main

on:
  push:
    # Publish `main` as `latest` tag.
    branches:
      - main

    # Publish version tags.
    tags:
      - v*

jobs:

  main:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: terminusdb/terminusdb
          path: terminusdb

      - name: Build image
        run: docker build . --tag terminusdb/terminusdb-builder:local

      - name: Run unit tests
        run: |
          docker run \
            --rm \
            --volume $(pwd)/terminusdb:/app/terminusdb \
            --workdir /app/terminusdb \
            terminusdb/terminusdb-builder:local \
            make test
