name: main

on:
  push:
    # Publish `main` as `latest` tag.
    branches:
      - main

    # Publish version tags.
    tags:
      - v*

jobs:

  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: terminusdb/terminusdb
          path: terminusdb

      - name: Build image
        run: docker build . --tag terminusdb/terminusdb-builder:base

      - name: Install dependencies
        run: |
          docker run \
            --name deps-installed \
            --volume $(pwd)/terminusdb:/app/terminusdb \
            --workdir /app/terminusdb \
            terminusdb/terminusdb-builder:base \
            make install-deps
          docker commit \
            deps-installed \
            terminusdb/terminusdb-builder:deps-installed

      - name: Lint
        run: |
          docker run \
            --rm \
            --volume $(pwd)/terminusdb:/app/terminusdb \
            --workdir /app/terminusdb \
            terminusdb/terminusdb-builder:deps-installed \
            make lint

      - name: Build executable
        run: |
          docker run \
            --name executable-built \
            --volume $(pwd)/terminusdb:/app/terminusdb \
            --workdir /app/terminusdb \
            terminusdb/terminusdb-builder:deps-installed \
            make
          docker commit \
            executable-built \
            terminusdb/terminusdb-builder:executable-built

      - name: Unit tests
        run: |
          docker run \
            --rm \
            --volume $(pwd)/terminusdb:/app/terminusdb \
            --workdir /app/terminusdb \
            terminusdb/terminusdb-builder:executable-built \
            make test

      - name: Integration tests
        run: |
          docker run \
            --rm \
            --volume $(pwd)/terminusdb:/app/terminusdb \
            --workdir /app/terminusdb \
            terminusdb/terminusdb-builder:executable-built \
            /app/terminusdb/terminusdb store init
          docker run \
            --name server-running \
            --detach \
            --net=host \
            --volume $(pwd)/terminusdb:/app/terminusdb \
            --workdir /app/terminusdb \
            terminusdb/terminusdb-builder:executable-built \
            /app/terminusdb/terminusdb serve
          docker run \
            --rm \
            --net=host \
            --volume $(pwd)/terminusdb:/app/terminusdb \
            --workdir /app/terminusdb/tests \
            terminusdb/terminusdb-builder:executable-built \
            /bin/bash -c "npm install-ci-check && npm run check"
          docker stop server-running
